[package]
name = "golem-libp2p"
version = "0.1.0"
authors = ["badb <a.skrzy@gmail.com>"]

[dependencies]
ethkey = { git = "https://github.com/badb/parity-ethereum", branch = "strip-down-ethkeys-ring-0.14" }
libp2p = "0.3.1"
rand = "0.6.5"
