[package]
name = "golem-libp2p"
version = "0.1.0"
authors = ["Adam Wierzbicki <awierzbicki@golem.network>"]
edition = "2018"

[dependencies]
futures = "0.1"
libp2p = "0.3.0"
tokio = "0.1"
tokio-io = "0.1"
void = "1.0"