[package]
name = "golem-libp2p"
version = "0.1.0"
authors = ["badb <a.skrzy@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
libp2p = { git = "https://github.com/libp2p/rust-libp2p" }
tokio-codec = "0.1"
tokio-current-thread = "0.1"
tokio-io = "0.1"
